version: '3.8'

services:
  # Authorization Server
  auth-server:
    build:
      context: ./AuthorizationServer
      dockerfile: Dockerfile
    container_name: auth-server
    ports:
      - "8080:8080"
    environment:
      - CORS_ALLOWED_ORIGINS=http://localhost:5173,http://localhost:80,http://client:80,http://react-client:80
      # - REACT_REDIRECT_URI=http://client:80/callback
      - REACT_POST_LOGOUT_URI=http://client:80
      - ISSUER_URI=http://auth-server:8080
      - REACT_REDIRECT_URI=http://localhost:5173/callback
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Resource Server
  resource-server:
    build:
      context: ./ResourceServer
      dockerfile: Dockerfile
    container_name: resource-server
    ports:
      - "9090:9090"
    environment:
    #   - SPRING_PROFILES_ACTIVE=docker
    #   - SERVER_PORT=9090
      # - KEYSET_URI=http://auth-server:8080/oauth2/jwks
      # - INTROSPECTION_URI=http://auth-server:8080/oauth2/introspect
      - CORS_ALLOWED_ORIGINS=http://localhost:5173,http://localhost:80,http://client:80,http://react-client:80
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://auth-server:8080/oauth2/jwks
      - ISSUER_URI=http://auth-server:8080
      - KEYSET_URI=http://auth-server:8080/oauth2/jwks
      - INTROSPECTION_URI=http://auth-server:8080/oauth2/introspect

    depends_on:
      auth-server:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/api/demo"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # React Client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "5173:80"
    environment:
      - REACT_APP_REDIRECT_URI=http://client:80/callback
      - REACT_APP_AUTH_SERVER_URL=http://auth-server:8080
    depends_on:
      - auth-server
      - resource-server
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
    name: oauth2-app-network
